### ISSUE TITLE
Whitespace to left of variables trimmed unexpectedly

### ISSUE THREAD

**Issue by kmonahan** [forumone/gesso#367] opened 2020-06-08 19:23 UTC
Sporadically, seems like spaces between classes are not displaying correctly in PHP 7.4+. Example: `page-title-area__wrapperl-constrain`. Also seen reports where the space between the ul tag and the classes is missing on the menu template. 

1. Possible to determine the cause/fix?
2. If not possible, need to make sure all templates set classes via a joined array and document in README.

**Comment by kmonahan** [comment] 2020-06-08 21:01
Seen with PHP 7.3/Node 12 as well when variable and string are mixed: `<div class="page-title-area__wrapper {{ constrain_classes }}">`

**Comment by kmonahan** [comment] 2020-06-10 21:16
Have not been able to reproduce the issue in `menu.twig` where there's no space between the `ul` tag and its attributes locally (although I did see it previously on a staging environment). However, I can reproduce the missing space when a string and a variable are combined.

Example test case, in page-title.twig
```
{% set classes = 'my-test-class' %}

<h1 class="page-title {{ classes }}">{{ page_title }}</h1>
```

Expected result: `<h1 class="page-title my-test-class">`
Actual result: `<h1 class="page-titlemy-test-class">`

**Comment by kmonahan** [comment] 2020-06-10 21:44
The reproducible issue appears to be fixed by updating to Pattern Lab 5.7.0. As Pattern Lab is now on 5.10.x, we should determine whether there are still any issues blocking update and, if not, move Gesso to a later release.

@coreylafferty, do you recall what was initially preventing us from moving to 5.7.x?

**Comment by coreylafferty** [comment] 2020-06-11 15:05
@kmonahan I've never liked the coding pattern like `<h1 class="page-title {{ classes }}">{{ page_title }}</h1>` because if 'classes' comes back false you end up with an extra space after the main class name.  Throughout Gesso we've switched to declaring an array of classes where this kind of thing is needed.  I also wonder if doing something like `<h1 class="page-title{% if classes %} {{ classes }}{% endif %}">{{ page_title }}</h1>` would also solve the problem.  

I'd been assuming this problem was coming from the version of PHP... either due to a bug or because it was newly implemented intended behavior (maybe b/c it's trying to trim trailing spaces, but that's happening before the classes variable is rendered?).

In any case, if updating the Pattern Lab version fixes this, then eventually we'll do that.  We're still blocked from upgrading until a problem with the rendering of the pattern menus is fixed.  There's an outstanding PR that fixes it.  As soon as that gets accepted (or something like it), I plan to update the version being used in Gesso.

https://github.com/pattern-lab/patternlab-node/pull/1143

**Comment by kmonahan** [comment] 2020-06-11 15:18
@coreylafferty,
The underlying issue here is that Pattern Lab is removing whitespace to the left of a variable output. (I was able to reproduce the issue as well by adding space between my tag and the content.) Although I couldn't get the menu issue to occur on my local, I strongly suspect it's related. I likewise prefer the array of classes approach, but regardless, whitespace being unexpectedly removed is a bug I'd like to see fixed. It's occurred in both PHP 7.3 and PHP 7.4, so less tied to the version of PHP than I thought initially.

Looking at the response to your question in that issue, sounds like it's close to being accepted, so hopefully we'll be able to update soon.

**Comment by kmonahan** [comment] 2020-06-11 15:20
In the mean time, workarounds for anyone who is hitting this issue:

- For CSS classes, combine all classes into an array (F1's preferred approach when needed variable classes)
- Flip the order of the string and the variable (at least in my testing, whitespace on the left was getting trimmed but not on the right)
- Try putting the variable inside a conditional `{% if classes %} {{ classes }}{% endif %}`

**Comment by kmonahan** [comment] 2020-06-12 20:24
Notes from conversation with @coreylafferty just now:

- Issue did not occur on his test Wordpress site using the same version of Pattern Lab
- For further investigation: does the issue occur in Pattern Lab only or in Pattern Lab and Drupal?
- For further investigation: does the issue occur in Wordpress or just Drupal?
- If issue can be reproduced in other ways (i.e. Drupal theme templates), is it consistently resolved by updating pattern lab?

**Comment by tomealter** [comment] 2020-06-25 18:59
> * Try putting the variable inside a conditional `{% if classes %} {{ classes }}{% endif %}`

Tried this, and it appeared to not help on the DOI project.

I also noticed on DOI that the `menu.twig` file was removing space on `<ul>` and `<li>` before `{{ add_attributes(additional_attributes) }}` Which resulted in `<ulclass="menu menu--main">`

**Comment by coreylafferty** [comment] 2020-06-30 22:06
Found a fix for this.  It appears to be related to the PHP version (and possibly the Node version) being used by buildkite on the dev site in our setup.  In the `.buildkite/pattern-lab_sh` file on my project, I updated these lines:

```
local node_image="node:10"
local php_image="php:7-cli"
local node_version=v10.16.2
local node_checksum=2779d04b1a9744bbb003a1a4476db2444b5f697034bc902a07dde4a8669ae6d0
```

to:

```
local node_image="node:12"
local php_image="php:7.3-cli"
local node_version=v12.18.2
local node_checksum=2d316e55994086e41761b0c657e0027e9d16d7160d3f8854cc9dc7615b99a526
``` 

That appears to have fixed the Pattern Lab issues building on the dev site.  I suspect it's an issue with PHP 7.4, but regardless of exactly which version(s) are causing the issue, this should fix things for the moment.

**Comment by coreylafferty** [comment] 2020-10-20 15:28
Closing this as I believe it is no longer a problem since updating PL and dependencies.

**Closed as completed by coreylafferty** 2020-10-20 15:28 UTC
